require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StrategiesController do

  # This should return the minimal set of attributes required to create a valid
  # Strategie. As you add validations to Strategie, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StrategiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET show" do
    it "assigns the requested strategie as @strategie" do
      strategie = Strategie.create! valid_attributes
      get :show, {:id => strategie.to_param}, valid_session
      assigns(:strategie).should eq(strategie)
    end
  end

  describe "GET edit" do
    it "assigns the requested strategie as @strategie" do
      strategie = Strategie.create! valid_attributes
      get :edit, {:id => strategie.to_param}, valid_session
      assigns(:strategie).should eq(strategie)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested strategie" do
        strategie = Strategie.create! valid_attributes
        # Assuming there are no other strategies in the database, this
        # specifies that the Strategie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Strategie.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => strategie.to_param, :strategie => { "these" => "params" }}, valid_session
      end

      it "assigns the requested strategie as @strategie" do
        strategie = Strategie.create! valid_attributes
        put :update, {:id => strategie.to_param, :strategie => valid_attributes}, valid_session
        assigns(:strategie).should eq(strategie)
      end

      it "redirects to the strategie" do
        strategie = Strategie.create! valid_attributes
        put :update, {:id => strategie.to_param, :strategie => valid_attributes}, valid_session
        response.should redirect_to(strategie)
      end
    end

    describe "with invalid params" do
      it "assigns the strategie as @strategie" do
        strategie = Strategie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Strategie.any_instance.stub(:save).and_return(false)
        put :update, {:id => strategie.to_param, :strategie => {  }}, valid_session
        assigns(:strategie).should eq(strategie)
      end

      it "re-renders the 'edit' template" do
        strategie = Strategie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Strategie.any_instance.stub(:save).and_return(false)
        put :update, {:id => strategie.to_param, :strategie => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

end
